local fetch = require("fetch")
local opts = {}
local NasaHorizons = {}

local file = io.open("planetData.txt", "w")

---@enum Planets
NasaHorizons.solarSystemCodes = {
    Sun = 10,
    Mercury = 199,
    Venus = 299,
    Earth = 399,
    Moon = 301,
    Mars = 499,
    Jupiter = 599,
    Saturn = 699,
    Uranus = 799,
    Neptune = 899
}

---Builds the URL for accessing the Nasa Horizons api
---@param name Planets 
---@param date string Ex: 2026-01-01 
---@return string url
function NasaHorizons.buildURL(name, date)
    local base = "https://ssd.jpl.nasa.gov/api/horizons.api"
    local params = {
        format      = "text",
        COMMAND     = string.format("'%s'", NasaHorizons.solarSystemCodes[name]),
        OBJ_DATA    = "'NO'",
        MAKE_EPHEM  = "'YES'",
        EPHEM_TYPE  = "'VECTORS'",
        VEC_TABLE   = "'2'",
        CENTER      = "'@10'",
        START_TIME  = string.format("'%s 00:00'", date),
        STOP_TIME   = string.format("'%s 00:01'", date),
        STEP_SIZE   = "'1%20d'",
        OUT_UNITS   = "'AU-D'",
        CSV_FORMAT  = "'YES'"
    }

    --Generated by chatgpt, honestly have no idea how it works, will have to revisit later
    local function buildURL(base, params)
        local parts = {}
        for k, v in pairs(params) do
            table.insert(parts, k .. "=" .. v)
        end
        return base .. "?" .. table.concat(parts, "&")
    end

    return buildURL(base, params)
end

function NasaHorizons.request(name, date)
    local file, err = io.open("planetData.txt", "w")

    local link = NasaHorizons.buildURL(name, date)

    fetch(link, opts, function(res)
        print(res.code) -- status number
        print(res.headers) -- table key/value
        print(res.body) -- raw string with the respose
        file:write(res.body)
        print(res.adapter) -- how the request was made
        file:close()
        return res.body
    end)
end

---Needs to be put in the current gamestate's update function
function NasaHorizons.update()
    fetch.update()
end

return NasaHorizons